For #10540: status can be a dict or a str.
GPLgithub/sg-otio pull request #41
Opened 2023-02-21 23:24 UTC by ksallee

Consider both cases, where status is a dict or where status is a str. Add a unittest to test both.

2023-02-22 10:34 UTC, gplsteph requested changes
The fix looks suspicious at first glance. In the end what is the expected value? A status or its code? It would be better to ensure that the value is consistent rather than being permissive here. This could cause problems in other parts of the code.

2023-02-22 10:34 UTC, gplsteph commented on sg_otio/cut_diff.py
> +                sg_shot_status = self.sg_shot_status
else?

2023-02-22 10:34 UTC, gplsteph commented on sg_otio/cut_diff.py
> +            elif isinstance(self.sg_shot_status, str):
this code is Py 3 only? Otherwise the test must be refined I think.

2023-02-22 22:03 UTC, ksallee commented
@gplsteph as suggested I checked, and there's no reason to have this as a dict.

2023-02-23 11:09 UTC, gplsteph approved these changes
Thanks for checking.

2023-02-28 22:12 UTC, merged